<?php
/**
 * Ledger Configuration
 * Generated by the installer on {{INSTALL_DATE}}
 */

return [
    'db' => [
        'host'     => '{{DB_HOST}}',
        'port'     => {{DB_PORT}},
        'username' => '{{DB_USER}}',
        'password' => '{{DB_PASS}}',
        'charset'  => 'utf8mb4',
    ],
    'app' => [
        'name'              => 'Ledger',
        'default_theme'     => 'light-clean',
        'rows_per_page'     => 50,
        'max_query_history'  => 50,
        'enable_export'     => true,
        'fonts' => [
            'general'  => '',
            'code'     => '',
            'sidebar'  => '',
            'data'     => '',
            'heading'  => '',
        ],
    ],
    'security' => [
        'require_auth'       => true,
        'users'              => [
            '{{ADMIN_USER}}' => '{{ADMIN_HASH}}',
        ],
        'session_lifetime'   => 3600,
        'session_name'       => 'LEDGER_SESSION',
        'csrf_enabled'       => true,
        'ip_whitelist'       => [],
        'force_https'        => false,
        'read_only'          => false,
        'hidden_databases'   => {{HIDDEN_DBS}},
        'query_log'          => false,
        'query_log_file'     => __DIR__ . '/logs/queries.log',
        'max_login_attempts' => 5,
        'lockout_duration'   => 300,
    ],
];
